const cidades = [
  { label: "Adamantina", value: 0 },
  { label: "Alfredo Marcondes", value: 1 },
  { label: "Álvares Machado", value: 2 },
  { label: "Anhumas", value: 3 },
  { label: "Caiabu", value: 4 },
  { label: "Caiuá", value: 5 },
  { label: "Dracena", value: 6 },
  { label: "Emilianópolis", value: 7 },
  { label: "Estrela do Norte", value: 8 },
  {
    label: "Euclides da Cunha Paulista",
    value: 9,
  },
  { label: "Flora Rica", value: 10 },
  { label: "Flórida Paulista", value: 11 },
  { label: "Iepê", value: 12 },
  { label: "Indiana", value: 13 },
  { label: "Inúbia Paulista", value: 14 },
  { label: "Irapuru", value: 15 },
  { label: "João Ramalho", value: 16 },
  { label: "Junqueirópolis", value: 17 },
  { label: "Lucélia", value: 18 },
  { label: "Marabá Paulista", value: 19 },
  { label: "Mariápolis", value: 20 },
  { label: "Martinópolis", value: 21 },
  {
    label: "Mirante do Paranapanema",
    value: 22,
  },
  { label: "Monte Castelo", value: 23 },
  { label: "Nantes", value: 24 },
  { label: "Narandiba", value: 25 },
  { label: "Nova Guataporanga", value: 26 },
  { label: "Osvaldo Cruz", value: 27 },
  { label: "Ouro Verde", value: 28 },
  { label: "Pacaembu", value: 29 },
  { label: "Panorama", value: 30 },
  { label: "Parapuã", value: 31 },
  { label: "Paulicéia", value: 32 },
  { label: "Piquerobi", value: 33 },
  { label: "Pirapozinho", value: 34 },
  { label: "Pracinha", value: 35 },
  { label: "Presidente Bernardes", value: 36 },
  { label: "Presidente Epitácio", value: 37 },
  { label: "Presidente Prudente", value: 38 },
  { label: "Presidente Venceslau", value: 39 },
  { label: "Rancharia", value: 40 },
  { label: "Regente Feijó", value: 41 },
  { label: "Ribeirão dos Índios", value: 42 },
  { label: "Rinópolis", value: 43 },
  { label: "Rosana", value: 44 },
  { label: "Sagres", value: 45 },
  { label: "Salmourão", value: 46 },
  { label: "Sandovalina", value: 47 },
  { label: "Santa Mercedes", value: 48 },
  { label: "Santo Anastácio", value: 49 },
  { label: "Santo Expedito", value: 50 },
  {
    label: "São João do Pau d'Alho",
    value: 51,
  },
  { label: "Taciba", value: 52 },
  { label: "Tarabai", value: 53 },
  { label: "Teodoro Sampaio", value: 54 },
  { label: "Tupi Paulista", value: 55 },
];

export default cidades;